version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    container_name: badges-frontend
    image: 'edxops/badges-frontend:latest'
    volumes:
      - '.:/edx/app:delegated'
      - 'notused:/edx/app/node_modules'
    ports:
      - '1991:1991'
    environment:
      - NODE_ENV=development

networks:
  default:
    external:
      name: devstack_default

volumes:
  notused: null
